ZLIB_LIBS = @ZLIB_LIBS@
ZLIB_CFLAGS = @ZLIB_CFLAGS@
LIBLZMA_LIBS = @LIBLZMA_LIBS@
LIBLZMA_CFLAGS = @LIBLZMA_CFLAGS@
LIBZSTD_LIBS = @LIBZSTD_LIBS@
LIBZSTD_CFLAGS = @LIBZSTD_CFLAGS@

if BUILD_EXAMPLES
MAYBE_EXAMPLES = examples
endif
SUBDIRS = src tests $(MAYBE_EXAMPLES)

lib_LTdir = $(libdir)

pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = libsqfs.pc

EXTRA_DIST = libsqfs.pc.in
